version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nginx
    # volumes:
    #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     - ./build:/usr/share/nginx/html
    ports:
      - "8080:80"
    # environment:
    #     - NGINX_HOST=foobar.com
    #     - NGINX_PORT=80
    restart: always
